// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEfu6tA04frDxiB5sEirgPMBcGAjN1BF4',
    appId: '1:287697396316:web:23598b54a45d649e183c99',
    messagingSenderId: '287697396316',
    projectId: 'biss-to-cli',
    authDomain: 'biss-to-cli.firebaseapp.com',
    storageBucket: 'biss-to-cli.appspot.com',
    measurementId: 'G-RMR6WYYH5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_fs5jkfPDrZAIVgK2msFmo8GVeXo1YsQ',
    appId: '1:287697396316:android:f338c50f6c010e80183c99',
    messagingSenderId: '287697396316',
    projectId: 'biss-to-cli',
    storageBucket: 'biss-to-cli.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfY49plSjGmeMH4KKDT5dCbgDzHm6AVDI',
    appId: '1:287697396316:ios:f576c73410ea8146183c99',
    messagingSenderId: '287697396316',
    projectId: 'biss-to-cli',
    storageBucket: 'biss-to-cli.appspot.com',
    iosBundleId: 'com.example.b2clients',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfY49plSjGmeMH4KKDT5dCbgDzHm6AVDI',
    appId: '1:287697396316:ios:f576c73410ea8146183c99',
    messagingSenderId: '287697396316',
    projectId: 'biss-to-cli',
    storageBucket: 'biss-to-cli.appspot.com',
    iosBundleId: 'com.example.b2clients',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEfu6tA04frDxiB5sEirgPMBcGAjN1BF4',
    appId: '1:287697396316:web:eed010eace3f78b9183c99',
    messagingSenderId: '287697396316',
    projectId: 'biss-to-cli',
    authDomain: 'biss-to-cli.firebaseapp.com',
    storageBucket: 'biss-to-cli.appspot.com',
    measurementId: 'G-L6XNVLYJDJ',
  );
}
